/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../src/ckeditor.module';
import * as import2 from '@angular/common';
class CKEditorModuleInjector extends import0.ɵNgModuleInjector<import1.CKEditorModule> {
  _CommonModule_0:import2.CommonModule;
  _CKEditorModule_1:import1.CKEditorModule;
  __NgLocalization_2:import2.NgLocaleLocalization;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  createInternal():import1.CKEditorModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._CKEditorModule_1 = new import1.CKEditorModule();
    return this._CKEditorModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.CKEditorModule)) { return this._CKEditorModule_1; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const CKEditorModuleNgFactory:import0.NgModuleFactory<import1.CKEditorModule> = new import0.NgModuleFactory<any>(CKEditorModuleInjector,import1.CKEditorModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYW5kcmV5L0NPREUvbmcyLWNrZWRpdG9yL3NyYy9ja2VkaXRvci5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9hbmRyZXkvQ09ERS9uZzItY2tlZGl0b3Ivc3JjL2NrZWRpdG9yLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
