/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../src/ckeditor.component';
import * as import2 from '@angular/forms';
const styles_CKEditorComponent:any[] = ([] as any[]);
export const RenderType_CKEditorComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_CKEditorComponent,
  data: {}
}
);
export function View_CKEditorComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵqud(402653184,1,{host: 0}),
    (l()(),import0.ɵeld(0,[
      [
        1,
        0
      ]
      ,
      [
        'host',
        1
      ]

    ]
    ,(null as any),0,'textarea',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)))
  ]
  ,(null as any),(null as any));
}
function View_CKEditorComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),4,'ckeditor',([] as any[]),(null as any),(null as any),(null as any),View_CKEditorComponent_0,RenderType_CKEditorComponent)),
    import0.ɵdid(4898816,(null as any),2,import1.CKEditorComponent,[import0.NgZone],(null as any),(null as any)),
    import0.ɵqud(603979776,1,{toolbarButtons: 1}),
    import0.ɵqud(603979776,2,{toolbarGroups: 1}),
    import0.ɵprd(5120,(null as any),import2.NG_VALUE_ACCESSOR,(p0_0:any) => {
      return [p0_0];
    },[import1.CKEditorComponent])
  ]
  ,(null as any),(null as any));
}
export const CKEditorComponentNgFactory:import0.ComponentFactory<import1.CKEditorComponent> = import0.ɵccf('ckeditor',import1.CKEditorComponent,View_CKEditorComponent_Host_0,{
  config: 'config',
  debounce: 'debounce',
  readonly: 'readonly',
  value: 'value'
}
,{
  change: 'change',
  ready: 'ready',
  blur: 'blur',
  focus: 'focus'
}
,([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYW5kcmV5L0NPREUvbmcyLWNrZWRpdG9yL3NyYy9ja2VkaXRvci5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9hbmRyZXkvQ09ERS9uZzItY2tlZGl0b3Ivc3JjL2NrZWRpdG9yLmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvYW5kcmV5L0NPREUvbmcyLWNrZWRpdG9yL3NyYy9ja2VkaXRvci5jb21wb25lbnQudHMuQ0tFZGl0b3JDb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvYW5kcmV5L0NPREUvbmcyLWNrZWRpdG9yL3NyYy9ja2VkaXRvci5jb21wb25lbnQudHMuQ0tFZGl0b3JDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8dGV4dGFyZWEgI2hvc3Q+PC90ZXh0YXJlYT4iLCI8Y2tlZGl0b3I+PC9ja2VkaXRvcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7Ozs7OztJQ0FBO2dCQUFBO2dCQUFBO2dCQUFBO2dCQUFBO01BQUE7SUFBQTs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
